######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Thu Jun 17 15:41:28 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"cpu_tb_time_synth.v" \
"../../../../54cpu.srcs/sources_1/new/test.v" \


quit -force

