######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Thu Jun 17 15:41:35 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
