# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.cache/wt} [current_project]
set_property parent.project_path {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{c:/Users/1234/Desktop/digit logical shortcut/ip_repo/myip_1.0}} [current_project]
add_files {{C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/mips_54_mars_simulate_student.coe}}
add_files {{C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/mips_54_mars_simulate_student_ForWeb.coe}}
add_files -quiet {{c:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/ip/imem/imem.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/ip/imem/imem.dcp}}]
read_verilog -library xil_defaultlib {
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/mux_8_1.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/mux_4_1_5bit.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/clz.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/MULTU.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/MULT.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/DIVU.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/DIV.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/cu.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/hiloreg.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/cp0.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/mux_16_1.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/mux_4_1.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/regfile.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/pcreg.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/ALU.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/seg7x16.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/DMEM.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/cpu.v}
  {C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/new/sccomp_dataflow.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/cpu_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/1234/Desktop/digit logical shortcut/54cpu-rboard/54cpu.srcs/sources_1/cpu_constraints.xdc}}]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
