######################################################################
#
# File name : sccomp_dataflow_simulate.do
# Created on: Wed Jun 16 19:51:52 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.sccomp_dataflow xil_defaultlib.glbl

do {sccomp_dataflow_wave.do}

view wave
view structure
view signals

do {sccomp_dataflow.udo}

run 1000ns
