######################################################################
#
# File name : sccomp_dataflow_compile.do
# Created on: Wed Jun 16 19:51:48 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"sccomp_dataflow_func_synth.v" \


quit -force

