######################################################################
#
# File name : sccomp_dataflow_wave.do
# Created on: Wed Jun 16 19:51:52 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
